extends SceneTree

# Run with the graphical renderer; baking requires the rendered skeleton pose.
# Regenerate after changing citizen.glb. No per-character GPU readback at runtime.
func _initialize() -> void:
	run.call_deferred()

func run() -> void:
	var model: Node3D = load("res://assets/models/characters/modular/citizen.glb").instantiate()
	root.add_child(model)
	var ap: AnimationPlayer = model.find_child("AnimationPlayer", true, false)
	ap.callback_mode_process = AnimationMixer.ANIMATION_CALLBACK_MODE_PROCESS_MANUAL
	var profiles := {}
	for bare in [false, true]:
		var kind := "bare" if bare else "shoes"
		profiles[kind] = {}
		for clip in ["idle", "walk", "run"]:
			ap.play(clip)
			var duration := ap.current_animation_length
			var count := int(ceil(duration * 120.0))
			var offsets: Array[float] = []
			for i in count + 1:
				ap.seek(duration * float(i % count) / count, true)
				await process_frame
				await RenderingServer.frame_post_draw
				var low := INF
				for mesh in model.find_children("*", "MeshInstance3D", true, false):
					if str(mesh.name) not in (["FootL", "FootR"] if bare else ["BootL", "BootR"]):
						continue
					var baked: ArrayMesh = mesh.bake_mesh_from_current_skeleton_pose()
					for surface in baked.get_surface_count():
						for vertex in baked.surface_get_arrays(surface)[Mesh.ARRAY_VERTEX]:
							low = minf(low, (mesh.global_transform * vertex).y)
				offsets.append(snappedf(0.002 - low, 0.000001))
			profiles[kind][clip] = {"duration": duration, "offsets": offsets}
			print("GROUND_PROFILE ", kind, " ", clip, " samples=", offsets.size())
	var file := FileAccess.open("res://scripts/ground_contact_profiles.gd", FileAccess.WRITE)
	file.store_string("# Generated by tools/build_ground_profiles.gd from citizen.glb.\n# Vertical contact correction, sampled at 120 Hz; meters.\nextends RefCounted\n\nconst MODEL_SHA256 = \"" + FileAccess.get_sha256("res://assets/models/characters/modular/citizen.glb") + "\"\nconst DATA = " + JSON.stringify(profiles, "\t") + "\n")
	file.close()
	model.queue_free()
	await process_frame
	quit()
